# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inference_pb2 as inference__pb2


class InferenceTrackerStub:
    """InferenceTracker service for YOLO->Compute gRPC stream
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        try:
            self.StreamResults = channel.stream_unary(
                    '/inference.InferenceTracker/StreamResults',
                    request_serializer=inference__pb2.YoloInferenceResult.SerializeToString,
                    response_deserializer=inference__pb2.Ack.FromString)
        except Exception:
            self.StreamResults = channel.stream_unary(
                    '/inference.InferenceTracker/StreamResults',
                    request_serializer=inference__pb2.InferenceResult.SerializeToString,
                    response_deserializer=inference__pb2.Ack.FromString)


class InferenceTrackerServicer:
    """InferenceTracker service for YOLO->Compute gRPC stream
    """

    def StreamResults(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceTrackerServicer_to_server(servicer, server):
    try:
        rpc_method_handlers = {
                'StreamResults': grpc.stream_unary_rpc_method_handler(
                        servicer.StreamResults,
                        request_deserializer=inference__pb2.YoloInferenceResult.FromString,
                        response_serializer=inference__pb2.Ack.SerializeToString,
                ),
        }
    except Exception:
        rpc_method_handlers = {
                'StreamResults': grpc.stream_unary_rpc_method_handler(
                        servicer.StreamResults,
                        request_deserializer=inference__pb2.InferenceResult.FromString,
                        response_serializer=inference__pb2.Ack.SerializeToString,
                ),
        }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
