// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: fw.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageTimestamps struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ClientCaptureMs          int64                  `protobuf:"varint,1,opt,name=client_capture_ms,json=clientCaptureMs,proto3" json:"client_capture_ms,omitempty"`
	SchedulerReceiveMs       int64                  `protobuf:"varint,2,opt,name=scheduler_receive_ms,json=schedulerReceiveMs,proto3" json:"scheduler_receive_ms,omitempty"`
	SchedulerDecisionMs      int64                  `protobuf:"varint,3,opt,name=scheduler_decision_ms,json=schedulerDecisionMs,proto3" json:"scheduler_decision_ms,omitempty"`
	ComputeReceiveMs         int64                  `protobuf:"varint,4,opt,name=compute_receive_ms,json=computeReceiveMs,proto3" json:"compute_receive_ms,omitempty"`
	UdpSendMs                int64                  `protobuf:"varint,5,opt,name=udp_send_ms,json=udpSendMs,proto3" json:"udp_send_ms,omitempty"`
	PythonReceiveMs          int64                  `protobuf:"varint,6,opt,name=python_receive_ms,json=pythonReceiveMs,proto3" json:"python_receive_ms,omitempty"`
	YoloInferenceStartMs     int64                  `protobuf:"varint,7,opt,name=yolo_inference_start_ms,json=yoloInferenceStartMs,proto3" json:"yolo_inference_start_ms,omitempty"`
	YoloInferenceEndMs       int64                  `protobuf:"varint,8,opt,name=yolo_inference_end_ms,json=yoloInferenceEndMs,proto3" json:"yolo_inference_end_ms,omitempty"`
	PythonGrpcSendMs         int64                  `protobuf:"varint,9,opt,name=python_grpc_send_ms,json=pythonGrpcSendMs,proto3" json:"python_grpc_send_ms,omitempty"`
	ComputeReceiveResultMs   int64                  `protobuf:"varint,10,opt,name=compute_receive_result_ms,json=computeReceiveResultMs,proto3" json:"compute_receive_result_ms,omitempty"`
	SchedulerReceiveResultMs int64                  `protobuf:"varint,11,opt,name=scheduler_receive_result_ms,json=schedulerReceiveResultMs,proto3" json:"scheduler_receive_result_ms,omitempty"`
	FrontendSendMs           int64                  `protobuf:"varint,12,opt,name=frontend_send_ms,json=frontendSendMs,proto3" json:"frontend_send_ms,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StageTimestamps) Reset() {
	*x = StageTimestamps{}
	mi := &file_fw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageTimestamps) ProtoMessage() {}

func (x *StageTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageTimestamps.ProtoReflect.Descriptor instead.
func (*StageTimestamps) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{0}
}

func (x *StageTimestamps) GetClientCaptureMs() int64 {
	if x != nil {
		return x.ClientCaptureMs
	}
	return 0
}

func (x *StageTimestamps) GetSchedulerReceiveMs() int64 {
	if x != nil {
		return x.SchedulerReceiveMs
	}
	return 0
}

func (x *StageTimestamps) GetSchedulerDecisionMs() int64 {
	if x != nil {
		return x.SchedulerDecisionMs
	}
	return 0
}

func (x *StageTimestamps) GetComputeReceiveMs() int64 {
	if x != nil {
		return x.ComputeReceiveMs
	}
	return 0
}

func (x *StageTimestamps) GetUdpSendMs() int64 {
	if x != nil {
		return x.UdpSendMs
	}
	return 0
}

func (x *StageTimestamps) GetPythonReceiveMs() int64 {
	if x != nil {
		return x.PythonReceiveMs
	}
	return 0
}

func (x *StageTimestamps) GetYoloInferenceStartMs() int64 {
	if x != nil {
		return x.YoloInferenceStartMs
	}
	return 0
}

func (x *StageTimestamps) GetYoloInferenceEndMs() int64 {
	if x != nil {
		return x.YoloInferenceEndMs
	}
	return 0
}

func (x *StageTimestamps) GetPythonGrpcSendMs() int64 {
	if x != nil {
		return x.PythonGrpcSendMs
	}
	return 0
}

func (x *StageTimestamps) GetComputeReceiveResultMs() int64 {
	if x != nil {
		return x.ComputeReceiveResultMs
	}
	return 0
}

func (x *StageTimestamps) GetSchedulerReceiveResultMs() int64 {
	if x != nil {
		return x.SchedulerReceiveResultMs
	}
	return 0
}

func (x *StageTimestamps) GetFrontendSendMs() int64 {
	if x != nil {
		return x.FrontendSendMs
	}
	return 0
}

type DecodedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FrameData     []byte                 `protobuf:"bytes,2,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedFrame) Reset() {
	*x = DecodedFrame{}
	mi := &file_fw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedFrame) ProtoMessage() {}

func (x *DecodedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedFrame.ProtoReflect.Descriptor instead.
func (*DecodedFrame) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{1}
}

func (x *DecodedFrame) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DecodedFrame) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

type InferenceResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessingStatus   uint64                 `protobuf:"varint,2,opt,name=processing_status,json=processingStatus,proto3" json:"processing_status,omitempty"`
	Detections         []*BoundingBox         `protobuf:"bytes,3,rep,name=detections,proto3" json:"detections,omitempty"`
	FrameId            string                 `protobuf:"bytes,4,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	StageTs            *StageTimestamps       `protobuf:"bytes,5,opt,name=stage_ts,json=stageTs,proto3" json:"stage_ts,omitempty"`
	InferenceLatencyMs float32                `protobuf:"fixed32,6,opt,name=inference_latency_ms,json=inferenceLatencyMs,proto3" json:"inference_latency_ms,omitempty"`
	StreamId           string                 `protobuf:"bytes,7,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	NodeName           string                 `protobuf:"bytes,8,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InferenceResult) Reset() {
	*x = InferenceResult{}
	mi := &file_fw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResult) ProtoMessage() {}

func (x *InferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResult.ProtoReflect.Descriptor instead.
func (*InferenceResult) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{2}
}

func (x *InferenceResult) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InferenceResult) GetProcessingStatus() uint64 {
	if x != nil {
		return x.ProcessingStatus
	}
	return 0
}

func (x *InferenceResult) GetDetections() []*BoundingBox {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *InferenceResult) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *InferenceResult) GetStageTs() *StageTimestamps {
	if x != nil {
		return x.StageTs
	}
	return nil
}

func (x *InferenceResult) GetInferenceLatencyMs() float32 {
	if x != nil {
		return x.InferenceLatencyMs
	}
	return 0
}

func (x *InferenceResult) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *InferenceResult) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint64                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint64                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Dx            uint64                 `protobuf:"varint,3,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            uint64                 `protobuf:"varint,4,opt,name=dy,proto3" json:"dy,omitempty"`                  // FIXED: was =5, skipping 4
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`             // FIXED: renumbered
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"` // FIXED: renumbered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_fw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{3}
}

func (x *BoundingBox) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetDx() uint64 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *BoundingBox) GetDy() uint64 {
	if x != nil {
		return x.Dy
	}
	return 0
}

func (x *BoundingBox) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type RTPPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Ssrc          uint32                 `protobuf:"varint,3,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	FrameId       string                 `protobuf:"bytes,4,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StageTs       *StageTimestamps       `protobuf:"bytes,6,opt,name=stage_ts,json=stageTs,proto3" json:"stage_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTPPacket) Reset() {
	*x = RTPPacket{}
	mi := &file_fw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTPPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTPPacket) ProtoMessage() {}

func (x *RTPPacket) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTPPacket.ProtoReflect.Descriptor instead.
func (*RTPPacket) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{4}
}

func (x *RTPPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RTPPacket) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *RTPPacket) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *RTPPacket) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *RTPPacket) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *RTPPacket) GetStageTs() *StageTimestamps {
	if x != nil {
		return x.StageTs
	}
	return nil
}

// New: For gRPC client->scheduler migration
type ClientFrame struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JpegData           []byte                 `protobuf:"bytes,1,opt,name=jpeg_data,json=jpegData,proto3" json:"jpeg_data,omitempty"`
	StreamId           string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	FrameId            string                 `protobuf:"bytes,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	CaptureTimestampMs int64                  `protobuf:"varint,4,opt,name=capture_timestamp_ms,json=captureTimestampMs,proto3" json:"capture_timestamp_ms,omitempty"`
	StageTs            *StageTimestamps       `protobuf:"bytes,5,opt,name=stage_ts,json=stageTs,proto3" json:"stage_ts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_fw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{5}
}

func (x *ClientFrame) GetJpegData() []byte {
	if x != nil {
		return x.JpegData
	}
	return nil
}

func (x *ClientFrame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ClientFrame) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *ClientFrame) GetCaptureTimestampMs() int64 {
	if x != nil {
		return x.CaptureTimestampMs
	}
	return 0
}

func (x *ClientFrame) GetStageTs() *StageTimestamps {
	if x != nil {
		return x.StageTs
	}
	return nil
}

type StreamSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PacketsReceived int32                  `protobuf:"varint,1,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamSummary) Reset() {
	*x = StreamSummary{}
	mi := &file_fw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSummary) ProtoMessage() {}

func (x *StreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSummary.ProtoReflect.Descriptor instead.
func (*StreamSummary) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{6}
}

func (x *StreamSummary) GetPacketsReceived() int32 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *StreamSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MeasureEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeasTime      *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=meas_time,json=measTime,proto3" json:"meas_time,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,6,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasureEvent) Reset() {
	*x = MeasureEvent{}
	mi := &file_fw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasureEvent) ProtoMessage() {}

func (x *MeasureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasureEvent.ProtoReflect.Descriptor instead.
func (*MeasureEvent) Descriptor() ([]byte, []int) {
	return file_fw_proto_rawDescGZIP(), []int{7}
}

func (x *MeasureEvent) GetMeasTime() *timestamp.Timestamp {
	if x != nil {
		return x.MeasTime
	}
	return nil
}

func (x *MeasureEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MeasureEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MeasureEvent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MeasureEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MeasureEvent) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_fw_proto protoreflect.FileDescriptor

const file_fw_proto_rawDesc = "" +
	"\n" +
	"\bfw.proto\x12\afwproto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x04\n" +
	"\x0fStageTimestamps\x12*\n" +
	"\x11client_capture_ms\x18\x01 \x01(\x03R\x0fclientCaptureMs\x120\n" +
	"\x14scheduler_receive_ms\x18\x02 \x01(\x03R\x12schedulerReceiveMs\x122\n" +
	"\x15scheduler_decision_ms\x18\x03 \x01(\x03R\x13schedulerDecisionMs\x12,\n" +
	"\x12compute_receive_ms\x18\x04 \x01(\x03R\x10computeReceiveMs\x12\x1e\n" +
	"\vudp_send_ms\x18\x05 \x01(\x03R\tudpSendMs\x12*\n" +
	"\x11python_receive_ms\x18\x06 \x01(\x03R\x0fpythonReceiveMs\x125\n" +
	"\x17yolo_inference_start_ms\x18\a \x01(\x03R\x14yoloInferenceStartMs\x121\n" +
	"\x15yolo_inference_end_ms\x18\b \x01(\x03R\x12yoloInferenceEndMs\x12-\n" +
	"\x13python_grpc_send_ms\x18\t \x01(\x03R\x10pythonGrpcSendMs\x129\n" +
	"\x19compute_receive_result_ms\x18\n" +
	" \x01(\x03R\x16computeReceiveResultMs\x12=\n" +
	"\x1bscheduler_receive_result_ms\x18\v \x01(\x03R\x18schedulerReceiveResultMs\x12(\n" +
	"\x10frontend_send_ms\x18\f \x01(\x03R\x0efrontendSendMs\"K\n" +
	"\fDecodedFrame\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x02 \x01(\fR\tframeData\"\xce\x02\n" +
	"\x0fInferenceResult\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12+\n" +
	"\x11processing_status\x18\x02 \x01(\x04R\x10processingStatus\x124\n" +
	"\n" +
	"detections\x18\x03 \x03(\v2\x14.fwproto.BoundingBoxR\n" +
	"detections\x12\x19\n" +
	"\bframe_id\x18\x04 \x01(\tR\aframeId\x123\n" +
	"\bstage_ts\x18\x05 \x01(\v2\x18.fwproto.StageTimestampsR\astageTs\x120\n" +
	"\x14inference_latency_ms\x18\x06 \x01(\x02R\x12inferenceLatencyMs\x12\x1b\n" +
	"\tstream_id\x18\a \x01(\tR\bstreamId\x12\x1b\n" +
	"\tnode_name\x18\b \x01(\tR\bnodeName\"\x7f\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x04R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x04R\x01y\x12\x0e\n" +
	"\x02dx\x18\x03 \x01(\x04R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x04 \x01(\x04R\x02dy\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\"\xbb\x01\n" +
	"\tRTPPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12\x12\n" +
	"\x04ssrc\x18\x03 \x01(\rR\x04ssrc\x12\x19\n" +
	"\bframe_id\x18\x04 \x01(\tR\aframeId\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\tR\bstreamId\x123\n" +
	"\bstage_ts\x18\x06 \x01(\v2\x18.fwproto.StageTimestampsR\astageTs\"\xc9\x01\n" +
	"\vClientFrame\x12\x1b\n" +
	"\tjpeg_data\x18\x01 \x01(\fR\bjpegData\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x19\n" +
	"\bframe_id\x18\x03 \x01(\tR\aframeId\x120\n" +
	"\x14capture_timestamp_ms\x18\x04 \x01(\x03R\x12captureTimestampMs\x123\n" +
	"\bstage_ts\x18\x05 \x01(\v2\x18.fwproto.StageTimestampsR\astageTs\"T\n" +
	"\rStreamSummary\x12)\n" +
	"\x10packets_received\x18\x01 \x01(\x05R\x0fpacketsReceived\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb5\x02\n" +
	"\fMeasureEvent\x127\n" +
	"\tmeas_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bmeasTime\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12<\n" +
	"\apayload\x18\x06 \x03(\v2\".fwproto.MeasureEvent.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdc\x01\n" +
	"\rComputeStream\x12?\n" +
	"\fOffloadImage\x12\x15.fwproto.DecodedFrame\x1a\x18.fwproto.InferenceResult\x12?\n" +
	"\vStreamVideo\x12\x12.fwproto.RTPPacket\x1a\x18.fwproto.InferenceResult(\x010\x01\x12I\n" +
	"\x12StreamDecodedVideo\x12\x15.fwproto.DecodedFrame\x1a\x18.fwproto.InferenceResult(\x010\x012U\n" +
	"\x0fSchedulerStream\x12B\n" +
	"\fStreamFrames\x12\x14.fwproto.ClientFrame\x1a\x18.fwproto.InferenceResult(\x010\x01B*Z(github.com/BuzzingTaz/fw-edge-apps/protob\x06proto3"

var (
	file_fw_proto_rawDescOnce sync.Once
	file_fw_proto_rawDescData []byte
)

func file_fw_proto_rawDescGZIP() []byte {
	file_fw_proto_rawDescOnce.Do(func() {
		file_fw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fw_proto_rawDesc), len(file_fw_proto_rawDesc)))
	})
	return file_fw_proto_rawDescData
}

var file_fw_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_fw_proto_goTypes = []any{
	(*StageTimestamps)(nil),     // 0: fwproto.StageTimestamps
	(*DecodedFrame)(nil),        // 1: fwproto.DecodedFrame
	(*InferenceResult)(nil),     // 2: fwproto.InferenceResult
	(*BoundingBox)(nil),         // 3: fwproto.BoundingBox
	(*RTPPacket)(nil),           // 4: fwproto.RTPPacket
	(*ClientFrame)(nil),         // 5: fwproto.ClientFrame
	(*StreamSummary)(nil),       // 6: fwproto.StreamSummary
	(*MeasureEvent)(nil),        // 7: fwproto.MeasureEvent
	nil,                         // 8: fwproto.MeasureEvent.PayloadEntry
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_fw_proto_depIdxs = []int32{
	3,  // 0: fwproto.InferenceResult.detections:type_name -> fwproto.BoundingBox
	0,  // 1: fwproto.InferenceResult.stage_ts:type_name -> fwproto.StageTimestamps
	0,  // 2: fwproto.RTPPacket.stage_ts:type_name -> fwproto.StageTimestamps
	0,  // 3: fwproto.ClientFrame.stage_ts:type_name -> fwproto.StageTimestamps
	9,  // 4: fwproto.MeasureEvent.meas_time:type_name -> google.protobuf.Timestamp
	8,  // 5: fwproto.MeasureEvent.payload:type_name -> fwproto.MeasureEvent.PayloadEntry
	1,  // 6: fwproto.ComputeStream.OffloadImage:input_type -> fwproto.DecodedFrame
	4,  // 7: fwproto.ComputeStream.StreamVideo:input_type -> fwproto.RTPPacket
	1,  // 8: fwproto.ComputeStream.StreamDecodedVideo:input_type -> fwproto.DecodedFrame
	5,  // 9: fwproto.SchedulerStream.StreamFrames:input_type -> fwproto.ClientFrame
	2,  // 10: fwproto.ComputeStream.OffloadImage:output_type -> fwproto.InferenceResult
	2,  // 11: fwproto.ComputeStream.StreamVideo:output_type -> fwproto.InferenceResult
	2,  // 12: fwproto.ComputeStream.StreamDecodedVideo:output_type -> fwproto.InferenceResult
	2,  // 13: fwproto.SchedulerStream.StreamFrames:output_type -> fwproto.InferenceResult
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_fw_proto_init() }
func file_fw_proto_init() {
	if File_fw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fw_proto_rawDesc), len(file_fw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fw_proto_goTypes,
		DependencyIndexes: file_fw_proto_depIdxs,
		MessageInfos:      file_fw_proto_msgTypes,
	}.Build()
	File_fw_proto = out.File
	file_fw_proto_goTypes = nil
	file_fw_proto_depIdxs = nil
}
