// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: fw.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeStream_OffloadImage_FullMethodName       = "/fwproto.ComputeStream/OffloadImage"
	ComputeStream_StreamVideo_FullMethodName        = "/fwproto.ComputeStream/StreamVideo"
	ComputeStream_StreamDecodedVideo_FullMethodName = "/fwproto.ComputeStream/StreamDecodedVideo"
)

// ComputeStreamClient is the client API for ComputeStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeStreamClient interface {
	OffloadImage(ctx context.Context, in *DecodedFrame, opts ...grpc.CallOption) (*InferenceResult, error)
	StreamVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RTPPacket, InferenceResult], error)
	StreamDecodedVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecodedFrame, InferenceResult], error)
}

type computeStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeStreamClient(cc grpc.ClientConnInterface) ComputeStreamClient {
	return &computeStreamClient{cc}
}

func (c *computeStreamClient) OffloadImage(ctx context.Context, in *DecodedFrame, opts ...grpc.CallOption) (*InferenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResult)
	err := c.cc.Invoke(ctx, ComputeStream_OffloadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeStreamClient) StreamVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RTPPacket, InferenceResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeStream_ServiceDesc.Streams[0], ComputeStream_StreamVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RTPPacket, InferenceResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeStream_StreamVideoClient = grpc.BidiStreamingClient[RTPPacket, InferenceResult]

func (c *computeStreamClient) StreamDecodedVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DecodedFrame, InferenceResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ComputeStream_ServiceDesc.Streams[1], ComputeStream_StreamDecodedVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DecodedFrame, InferenceResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeStream_StreamDecodedVideoClient = grpc.BidiStreamingClient[DecodedFrame, InferenceResult]

// ComputeStreamServer is the server API for ComputeStream service.
// All implementations must embed UnimplementedComputeStreamServer
// for forward compatibility.
type ComputeStreamServer interface {
	OffloadImage(context.Context, *DecodedFrame) (*InferenceResult, error)
	StreamVideo(grpc.BidiStreamingServer[RTPPacket, InferenceResult]) error
	StreamDecodedVideo(grpc.BidiStreamingServer[DecodedFrame, InferenceResult]) error
	mustEmbedUnimplementedComputeStreamServer()
}

// UnimplementedComputeStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeStreamServer struct{}

func (UnimplementedComputeStreamServer) OffloadImage(context.Context, *DecodedFrame) (*InferenceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method OffloadImage not implemented")
}
func (UnimplementedComputeStreamServer) StreamVideo(grpc.BidiStreamingServer[RTPPacket, InferenceResult]) error {
	return status.Error(codes.Unimplemented, "method StreamVideo not implemented")
}
func (UnimplementedComputeStreamServer) StreamDecodedVideo(grpc.BidiStreamingServer[DecodedFrame, InferenceResult]) error {
	return status.Error(codes.Unimplemented, "method StreamDecodedVideo not implemented")
}
func (UnimplementedComputeStreamServer) mustEmbedUnimplementedComputeStreamServer() {}
func (UnimplementedComputeStreamServer) testEmbeddedByValue()                       {}

// UnsafeComputeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeStreamServer will
// result in compilation errors.
type UnsafeComputeStreamServer interface {
	mustEmbedUnimplementedComputeStreamServer()
}

func RegisterComputeStreamServer(s grpc.ServiceRegistrar, srv ComputeStreamServer) {
	// If the following call panics, it indicates UnimplementedComputeStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeStream_ServiceDesc, srv)
}

func _ComputeStream_OffloadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodedFrame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeStreamServer).OffloadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeStream_OffloadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeStreamServer).OffloadImage(ctx, req.(*DecodedFrame))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeStream_StreamVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeStreamServer).StreamVideo(&grpc.GenericServerStream[RTPPacket, InferenceResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeStream_StreamVideoServer = grpc.BidiStreamingServer[RTPPacket, InferenceResult]

func _ComputeStream_StreamDecodedVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeStreamServer).StreamDecodedVideo(&grpc.GenericServerStream[DecodedFrame, InferenceResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ComputeStream_StreamDecodedVideoServer = grpc.BidiStreamingServer[DecodedFrame, InferenceResult]

// ComputeStream_ServiceDesc is the grpc.ServiceDesc for ComputeStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fwproto.ComputeStream",
	HandlerType: (*ComputeStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OffloadImage",
			Handler:    _ComputeStream_OffloadImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVideo",
			Handler:       _ComputeStream_StreamVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDecodedVideo",
			Handler:       _ComputeStream_StreamDecodedVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fw.proto",
}

const (
	SchedulerStream_StreamFrames_FullMethodName = "/fwproto.SchedulerStream/StreamFrames"
)

// SchedulerStreamClient is the client API for SchedulerStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// New: Client->Scheduler gRPC service (replaces WebSocket for frame streaming)
type SchedulerStreamClient interface {
	StreamFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, InferenceResult], error)
}

type schedulerStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerStreamClient(cc grpc.ClientConnInterface) SchedulerStreamClient {
	return &schedulerStreamClient{cc}
}

func (c *schedulerStreamClient) StreamFrames(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, InferenceResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SchedulerStream_ServiceDesc.Streams[0], SchedulerStream_StreamFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, InferenceResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerStream_StreamFramesClient = grpc.BidiStreamingClient[ClientFrame, InferenceResult]

// SchedulerStreamServer is the server API for SchedulerStream service.
// All implementations must embed UnimplementedSchedulerStreamServer
// for forward compatibility.
//
// New: Client->Scheduler gRPC service (replaces WebSocket for frame streaming)
type SchedulerStreamServer interface {
	StreamFrames(grpc.BidiStreamingServer[ClientFrame, InferenceResult]) error
	mustEmbedUnimplementedSchedulerStreamServer()
}

// UnimplementedSchedulerStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerStreamServer struct{}

func (UnimplementedSchedulerStreamServer) StreamFrames(grpc.BidiStreamingServer[ClientFrame, InferenceResult]) error {
	return status.Error(codes.Unimplemented, "method StreamFrames not implemented")
}
func (UnimplementedSchedulerStreamServer) mustEmbedUnimplementedSchedulerStreamServer() {}
func (UnimplementedSchedulerStreamServer) testEmbeddedByValue()                         {}

// UnsafeSchedulerStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerStreamServer will
// result in compilation errors.
type UnsafeSchedulerStreamServer interface {
	mustEmbedUnimplementedSchedulerStreamServer()
}

func RegisterSchedulerStreamServer(s grpc.ServiceRegistrar, srv SchedulerStreamServer) {
	// If the following call panics, it indicates UnimplementedSchedulerStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerStream_ServiceDesc, srv)
}

func _SchedulerStream_StreamFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulerStreamServer).StreamFrames(&grpc.GenericServerStream[ClientFrame, InferenceResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SchedulerStream_StreamFramesServer = grpc.BidiStreamingServer[ClientFrame, InferenceResult]

// SchedulerStream_ServiceDesc is the grpc.ServiceDesc for SchedulerStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fwproto.SchedulerStream",
	HandlerType: (*SchedulerStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFrames",
			Handler:       _SchedulerStream_StreamFrames_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fw.proto",
}
