// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: inference.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceTracker_StreamResults_FullMethodName = "/inference.InferenceTracker/StreamResults"
)

// InferenceTrackerClient is the client API for InferenceTracker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferenceTracker service for YOLO->Compute gRPC stream
type InferenceTrackerClient interface {
	StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[YoloInferenceResult, Ack], error)
}

type inferenceTrackerClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceTrackerClient(cc grpc.ClientConnInterface) InferenceTrackerClient {
	return &inferenceTrackerClient{cc}
}

func (c *inferenceTrackerClient) StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[YoloInferenceResult, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceTracker_ServiceDesc.Streams[0], InferenceTracker_StreamResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[YoloInferenceResult, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceTracker_StreamResultsClient = grpc.ClientStreamingClient[YoloInferenceResult, Ack]

// InferenceTrackerServer is the server API for InferenceTracker service.
// All implementations must embed UnimplementedInferenceTrackerServer
// for forward compatibility.
//
// InferenceTracker service for YOLO->Compute gRPC stream
type InferenceTrackerServer interface {
	StreamResults(grpc.ClientStreamingServer[YoloInferenceResult, Ack]) error
	mustEmbedUnimplementedInferenceTrackerServer()
}

// UnimplementedInferenceTrackerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceTrackerServer struct{}

func (UnimplementedInferenceTrackerServer) StreamResults(grpc.ClientStreamingServer[YoloInferenceResult, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamResults not implemented")
}
func (UnimplementedInferenceTrackerServer) mustEmbedUnimplementedInferenceTrackerServer() {}
func (UnimplementedInferenceTrackerServer) testEmbeddedByValue()                          {}

// UnsafeInferenceTrackerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceTrackerServer will
// result in compilation errors.
type UnsafeInferenceTrackerServer interface {
	mustEmbedUnimplementedInferenceTrackerServer()
}

func RegisterInferenceTrackerServer(s grpc.ServiceRegistrar, srv InferenceTrackerServer) {
	// If the following call panics, it indicates UnimplementedInferenceTrackerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceTracker_ServiceDesc, srv)
}

func _InferenceTracker_StreamResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceTrackerServer).StreamResults(&grpc.GenericServerStream[YoloInferenceResult, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceTracker_StreamResultsServer = grpc.ClientStreamingServer[YoloInferenceResult, Ack]

// InferenceTracker_ServiceDesc is the grpc.ServiceDesc for InferenceTracker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceTracker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.InferenceTracker",
	HandlerType: (*InferenceTrackerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResults",
			Handler:       _InferenceTracker_StreamResults_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "inference.proto",
}
