// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// YoloBoundingBox: YOLO-specific bounding box format
// DIFFERENT from fwproto.BoundingBox to avoid conflict
type YoloBoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassLabel    string                 `protobuf:"bytes,1,opt,name=class_label,json=classLabel,proto3" json:"class_label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,5,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,6,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YoloBoundingBox) Reset() {
	*x = YoloBoundingBox{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YoloBoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YoloBoundingBox) ProtoMessage() {}

func (x *YoloBoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YoloBoundingBox.ProtoReflect.Descriptor instead.
func (*YoloBoundingBox) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *YoloBoundingBox) GetClassLabel() string {
	if x != nil {
		return x.ClassLabel
	}
	return ""
}

func (x *YoloBoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *YoloBoundingBox) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *YoloBoundingBox) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *YoloBoundingBox) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *YoloBoundingBox) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

// YoloInferenceResult: Result from YOLO to Compute
// DIFFERENT from fwproto.InferenceResult to avoid conflict
type YoloInferenceResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Timestamp          int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Boxes              []*YoloBoundingBox     `protobuf:"bytes,2,rep,name=boxes,proto3" json:"boxes,omitempty"`
	FrameId            string                 `protobuf:"bytes,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	InferenceLatencyMs float32                `protobuf:"fixed32,4,opt,name=inference_latency_ms,json=inferenceLatencyMs,proto3" json:"inference_latency_ms,omitempty"`
	YoloStartMs        int64                  `protobuf:"varint,5,opt,name=yolo_start_ms,json=yoloStartMs,proto3" json:"yolo_start_ms,omitempty"`
	YoloEndMs          int64                  `protobuf:"varint,6,opt,name=yolo_end_ms,json=yoloEndMs,proto3" json:"yolo_end_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *YoloInferenceResult) Reset() {
	*x = YoloInferenceResult{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YoloInferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YoloInferenceResult) ProtoMessage() {}

func (x *YoloInferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YoloInferenceResult.ProtoReflect.Descriptor instead.
func (*YoloInferenceResult) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *YoloInferenceResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *YoloInferenceResult) GetBoxes() []*YoloBoundingBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

func (x *YoloInferenceResult) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

func (x *YoloInferenceResult) GetInferenceLatencyMs() float32 {
	if x != nil {
		return x.InferenceLatencyMs
	}
	return 0
}

func (x *YoloInferenceResult) GetYoloStartMs() int64 {
	if x != nil {
		return x.YoloStartMs
	}
	return 0
}

func (x *YoloInferenceResult) GetYoloEndMs() int64 {
	if x != nil {
		return x.YoloEndMs
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\tinference\"\x8a\x01\n" +
	"\x0fYoloBoundingBox\x12\x1f\n" +
	"\vclass_label\x18\x01 \x01(\tR\n" +
	"classLabel\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x05 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x06 \x01(\x05R\x01h\"\xf6\x01\n" +
	"\x13YoloInferenceResult\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x120\n" +
	"\x05boxes\x18\x02 \x03(\v2\x1a.inference.YoloBoundingBoxR\x05boxes\x12\x19\n" +
	"\bframe_id\x18\x03 \x01(\tR\aframeId\x120\n" +
	"\x14inference_latency_ms\x18\x04 \x01(\x02R\x12inferenceLatencyMs\x12\"\n" +
	"\ryolo_start_ms\x18\x05 \x01(\x03R\vyoloStartMs\x12\x1e\n" +
	"\vyolo_end_ms\x18\x06 \x01(\x03R\tyoloEndMs\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2U\n" +
	"\x10InferenceTracker\x12A\n" +
	"\rStreamResults\x12\x1e.inference.YoloInferenceResult\x1a\x0e.inference.Ack(\x01B*Z(github.com/BuzzingTaz/fw-edge-apps/protob\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inference_proto_goTypes = []any{
	(*YoloBoundingBox)(nil),     // 0: inference.YoloBoundingBox
	(*YoloInferenceResult)(nil), // 1: inference.YoloInferenceResult
	(*Ack)(nil),                 // 2: inference.Ack
}
var file_inference_proto_depIdxs = []int32{
	0, // 0: inference.YoloInferenceResult.boxes:type_name -> inference.YoloBoundingBox
	1, // 1: inference.InferenceTracker.StreamResults:input_type -> inference.YoloInferenceResult
	2, // 2: inference.InferenceTracker.StreamResults:output_type -> inference.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
