# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
try:
    from google.protobuf import runtime_version as _runtime_version
    _runtime_version.ValidateProtobufRuntimeVersion(
        _runtime_version.Domain.PUBLIC,
        6,
        33,
        5,
        '',
        'inference.proto'
    )
except ImportError:
    pass
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"f\n\x0fYoloBoundingBox\x12\x13\n\x0b\x63lass_label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\x12\t\n\x01w\x18\x05 \x01(\x05\x12\t\n\x01h\x18\x06 \x01(\x05\"\xaf\x01\n\x13YoloInferenceResult\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12)\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\x1a.inference.YoloBoundingBox\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\x12\x1c\n\x14inference_latency_ms\x18\x04 \x01(\x02\x12\x15\n\ryolo_start_ms\x18\x05 \x01(\x03\x12\x13\n\x0byolo_end_ms\x18\x06 \x01(\x03\"\x17\n\x03\x41\x63k\x12\x10\n\x08received\x18\x01 \x01(\x08\x32U\n\x10InferenceTracker\x12\x41\n\rStreamResults\x12\x1e.inference.YoloInferenceResult\x1a\x0e.inference.Ack(\x01\x42*Z(github.com/BuzzingTaz/fw-edge-apps/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/BuzzingTaz/fw-edge-apps/proto'
  _globals['_YOLOBOUNDINGBOX']._serialized_start=30
  _globals['_YOLOBOUNDINGBOX']._serialized_end=132
  _globals['_YOLOINFERENCERESULT']._serialized_start=135
  _globals['_YOLOINFERENCERESULT']._serialized_end=310
  _globals['_ACK']._serialized_start=312
  _globals['_ACK']._serialized_end=335
  _globals['_INFERENCETRACKER']._serialized_start=337
  _globals['_INFERENCETRACKER']._serialized_end=422
# @@protoc_insertion_point(module_scope)
