# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

# Version check bypassed for compatibility


class InferenceTrackerStub:
    """InferenceTracker service for YOLO->Compute gRPC stream
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamResults = channel.stream_unary(
                '/inference.InferenceTracker/StreamResults',
                request_serializer=inference__pb2.YoloInferenceResult.SerializeToString,
                response_deserializer=inference__pb2.Ack.FromString,
                _registered_method=True)


class InferenceTrackerServicer:
    """InferenceTracker service for YOLO->Compute gRPC stream
    """

    def StreamResults(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceTrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamResults': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamResults,
                    request_deserializer=inference__pb2.YoloInferenceResult.FromString,
                    response_serializer=inference__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.InferenceTracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceTracker:
    """InferenceTracker service for YOLO->Compute gRPC stream
    """

    @staticmethod
    def StreamResults(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/inference.InferenceTracker/StreamResults',
            inference__pb2.YoloInferenceResult.SerializeToString,
            inference__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
